name: Auto Tag on Push

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for tags

      # Set up Git
      - name: Set up Git
        run: |
          git config --global user.name "Kunal726"
          git config --global user.email "kunalkulthe1@gmail.com"

      # Delete existing tag if it exists
      - name: Delete existing tag
        run: |
          git tag -d v0.0.1 || true
          git push origin :refs/tags/v0.0.1 || true

      # Create and push the tag
      - name: Create and push tag
        run: |
          git tag v0.0.1
          git push origin v0.0.1
